In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
from gtts import gTTS
import os
from pygame import mixer


In [2]:
df = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/connectionist-bench/sonar/sonar.all-data",header = None,index_col =None)

In [3]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9  ...      51      52      53      54      55      56      57      58  \
0  0.2111 ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  0.0090   
1  0.2872 ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049  0.0052   
2  0.6194 ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164  0.0095   
3  0.1264 ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044  0.0040   
4  0.4459 ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048  0.0107   

       59  60  
0  0.0032   R  
1  0.0044   R  
2  0.0078   R  
3  0.0117   R  
4  0.0094   R  

[5 rows x 61 columns]

In [4]:
df.tail()

0       1       2       3       4       5       6       7       8   \
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9  ...      51      52      53      54      55      56      57  \
203  0.2684 ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154 ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529 ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354 ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354 ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
203  0.0193  0.0157   M  
204  0.0062  0.0067   M  
205  0.0077  0.0031   M  
206  0.0036  0.0048   M  
207  0.0061  0.0115   M  

[5 rows x 61 columns]

In [5]:
array = df.values

In [6]:
x= array[:,0:60]
y = array[:,60]

In [7]:
df.shape

(208, 61)

In [8]:
le = LabelEncoder().fit(y)
le.transform(y)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0], dtype=int64)

In [9]:
sc = StandardScaler().fit(x)
x=sc.transform(x)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [10]:
x_train , x_test ,y_train,y_test = train_test_split(x,y,test_size = 0.20, random_state = 10)

In [11]:
clf = MLPClassifier()
clf.fit(x_train, y_train)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [12]:
score = clf.score(x_test,y_test)
print(score)

0.809523809524


In [14]:
#this is a sample for the rock sonar for testing
r_test=[0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,0.1609,0.1582,0.2238,0.0645,0.0660,0.2273,
        0.3100,0.2999,0.5078,0.4797,0.5783,0.5071,0.4328,0.5550,0.6711,0.6415,0.7104,0.8080,0.6791,0.3857,0.1307,0.2604,
        0.5121,0.7547,0.8537,0.8507,0.6692,0.6097,0.4943,0.2744,0.0510,0.2834,0.2825,0.4256,0.2641,0.1386,0.1051,0.1343,
        0.0383,0.0324,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032]
r_test =np.array(r_test)
r_test

array([ 0.02  ,  0.0371,  0.0428,  0.0207,  0.0954,  0.0986,  0.1539,
        0.1601,  0.3109,  0.2111,  0.1609,  0.1582,  0.2238,  0.0645,
        0.066 ,  0.2273,  0.31  ,  0.2999,  0.5078,  0.4797,  0.5783,
        0.5071,  0.4328,  0.555 ,  0.6711,  0.6415,  0.7104,  0.808 ,
        0.6791,  0.3857,  0.1307,  0.2604,  0.5121,  0.7547,  0.8537,
        0.8507,  0.6692,  0.6097,  0.4943,  0.2744,  0.051 ,  0.2834,
        0.2825,  0.4256,  0.2641,  0.1386,  0.1051,  0.1343,  0.0383,
        0.0324,  0.0232,  0.0027,  0.0065,  0.0159,  0.0072,  0.0167,
        0.018 ,  0.0084,  0.009 ,  0.0032])

In [15]:
#sample for the mine
m_test =[0.0587,0.1210,0.1268,0.1498,0.1436,0.0561,0.0832,0.0672,0.1372,0.2352,0.3208,0.4257,0.5201,0.4914,0.5950,0.7221,
         0.9039,0.9111,0.8723,0.7686,0.7326,0.5222,0.3097,0.3172,0.2270,0.1640,0.1746,0.1835,0.2048,0.1674,0.2767,0.3104,
         0.3399,0.4441,0.5046,0.2814,0.1681,0.2633,0.3198,0.1933,0.0934,0.0443,0.0780,0.0722,0.0405,0.0553,0.1081,0.1139,
         0.0767,0.0265,0.0215,0.0331,0.0111,0.0088,0.0158,0.0122,0.0038,0.0101,0.0228,0.0124]
m_test = np.array(m_test)
m_test

array([ 0.0587,  0.121 ,  0.1268,  0.1498,  0.1436,  0.0561,  0.0832,
        0.0672,  0.1372,  0.2352,  0.3208,  0.4257,  0.5201,  0.4914,
        0.595 ,  0.7221,  0.9039,  0.9111,  0.8723,  0.7686,  0.7326,
        0.5222,  0.3097,  0.3172,  0.227 ,  0.164 ,  0.1746,  0.1835,
        0.2048,  0.1674,  0.2767,  0.3104,  0.3399,  0.4441,  0.5046,
        0.2814,  0.1681,  0.2633,  0.3198,  0.1933,  0.0934,  0.0443,
        0.078 ,  0.0722,  0.0405,  0.0553,  0.1081,  0.1139,  0.0767,
        0.0265,  0.0215,  0.0331,  0.0111,  0.0088,  0.0158,  0.0122,
        0.0038,  0.0101,  0.0228,  0.0124])

In [17]:

prediction = clf.predict(m_test)

if prediction=="R":
    tts = gTTS(text='its a rock proceed with caution', lang='en')
    tts.save("gooda.mp3")
    os.system("mpg321 good.mp3")
    mixer.init()
    mixer.music.load('gooda.mp3')
    mixer.music.play()
else:
    tts = gTTS(text='stop its a mine do not proceed', lang='en')
    tts.save("goodb.mp3")
    os.system("mpg321 good.mp3")
    mixer.init()
    mixer.music.load('goodb.mp3')
    mixer.music.play()
    

C:\Users\User\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
